cookie:
  expiry_days: 30
  key: humand-sales-insights-secret-cookie-key-2024
  name: humand_insights_auth
credentials:
  usernames:
    augusto.ferrer:
      email: augusto.ferrer@humand.co
      failed_login_attempts: 0
      first_name: Augusto
      last_name: Ferrer
      logged_in: false
      password: $2b$12$NamiW6VbImi8tAG/vV26uOn06JAWMXBtAb3BRTmqEg.3Luu/.Z6a.
      roles:
      - viewer
    juan.diego.alcocer:
      email: juan.diego.alcocer@humand.co
      failed_login_attempts: 0
      first_name: Juandi
      last_name: Alcocer
      logged_in: false
      password: $2b$12$twTNt.4ruJEL0fxo.BMZvOSV/Ls5uq67669Lm2IE7SPn0BsQma2CO
      roles:
      - viewer
    juanba.scelzi:
      email: juanba.scelzi@humand.co
      failed_login_attempts: 0
      first_name: Juanba
      last_name: Scelzi
      logged_in: false
      password: $2b$12$XZj.bOdEV3c7mk66ZRfeaO6AaMWU93l/vol7zGn/ieXUtnYjqkrw6
      roles:
      - admin
    manuela.cavallo:
      email: manuela.cavallo@humand.co
      failed_login_attempts: 0
      first_name: Manuela
      last_name: Cavallo
      logged_in: false
      password: $2b$12$JC7uxRhAda/Q.zF6SunNrOWlBdipJjufxh5T6shz1yvYbgVHvChVG
      roles:
      - viewer
    nico.cordes:
      email: nico.cordes@humand.co
      failed_login_attempts: 0
      first_name: Nico
      last_name: Cordes
      logged_in: false
      password: $2b$12$9zZKOOoyJg7Yl91.9cDZbedT9jHrCGfKhMOm4t0qAmdLrhbjOYId.
      roles:
      - viewer
    soledad.barca:
      email: soledad.barca@humand.co
      failed_login_attempts: 0
      first_name: Sole
      last_name: Barca
      logged_in: false
      password: $2b$12$f7MjRwBhTCHKwNUf6.pLpeeuN5ZorT4ESnGnzY2vQPbCRDtIVg4DK
      roles:
      - viewer
    pedro:
      email: pedro@humand.co
      failed_login_attempts: 0
      first_name: Pedro
      last_name: ''
      logged_in: false
      password: $2b$12$c/1n09t29UpAYtu5EgFgde0PDXAJL9j.xnXQKf0rfKb1Gqs7r7rYe
      roles:
      - viewer
    salvador.castrobay:
      email: salvador.castrobay@humand.co
      failed_login_attempts: 0
      first_name: Salvador
      last_name: Castro Bay
      logged_in: false
      password: $2b$12$MgnOVLaK9uRYOKfbTXhb1eYpkIGvd28O40C7qem5Xu1N9fkjIRuA6
      roles:
      - admin
    marcos.palacio:
      email: marcos.palacio@humand.co
      failed_login_attempts: 0
      first_name: Marcos
      last_name: Palacio
      logged_in: false
      password: $2b$12$ltDv46FPA.9ubL/DoOzltukjEbzGFsJLNlujg0tzg7wO64ZRAQP0G
      roles:
      - viewer
    raphael.montressor:
      email: raphael.montressor@humand.co
      failed_login_attempts: 0
      first_name: Raphael
      last_name: Montressor
      logged_in: false
      password: $2b$12$sEYDjzIjRmbpB7hTymTIBu/oPbkOjo4BXIjFXxlYr8ZoW2Nmvfype
      roles:
      - viewer
    vanina.moreira:
      email: vanina.moreira@humand.co
      failed_login_attempts: 0
      first_name: Vanina
      last_name: Moreira
      logged_in: false
      password: $2b$12$SN/NaA/SO2MxhdtLD5QY3.ky1YS4Soim1PqKwxArRWEtPt2Qzq7ti
      roles:
      - viewer
    aimee:
      email: aimee@humand.co
      failed_login_attempts: 0
      first_name: Aimee
      last_name: ''
      logged_in: false
      password: $2b$12$WzTJ1rtOEf.kVZTs9Z8SNOA.mtKpweoaJfTr8bBrD/LToRHHcdKKm
      roles:
      - viewer
    vivi:
      email: vivi@humand.co
      failed_login_attempts: 0
      first_name: Vivi
      last_name: ''
      logged_in: false
      password: $2b$12$ExvM1zGIXRnewTqtyxf6c.nVo9T1kfg4C2Ay1qhzmG3OE7Hr0yCyC
      roles:
      - viewer
    luciano.paradiso:
      email: luciano.paradiso@humand.co
      failed_login_attempts: 0
      first_name: Lucho
      last_name: Paradiso
      logged_in: false
      password: $2b$12$JWqlgLQeV3AZld1xUJY2EOMzyYb3L7/LvIVNIJIn34CtJGt.z7yZq
      roles:
      - viewer
    agustina.ini:
      email: agustina.ini@humand.co
      failed_login_attempts: 0
      first_name: Agus
      last_name: Ini
      logged_in: false
      password: $2b$12$FOvij58iAnm16klIGLhaE.6ke1j4jTRykc8uQF6d7LlVut4aNqS3C
      roles:
      - viewer
pre-authorized:
  emails: []
